repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
{%- if cookiecutter.enable_protect_branches == 'y' %}
    -   id: no-commit-to-branch
        args: ["-b", "main", "-b", "dev"]
{%- endif %}
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ["--max-line-length", "79", "--extend-ignore", "E203"]
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
        args:
        -   "--target-version=py36"
        -   "--target-version=py37"
        -   "--target-version=py38"
        -   "--target-version=py39"
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black"]
{%- if cookiecutter.enable_mypy == 'y' %}
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    -   id: mypy
{%- if cookiecutter.enable_pydantic == 'y' %}
        additional_dependencies: [pydantic]
{%- endif %}
{%- endif %}
